AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for GumpsSearchEngine


Resources:
  DynamoIndexSQS:
        Type: AWS::SQS::Queue

  DynamoIndexSNS:
    Type: AWS::SNS::Topic
    Properties:  
      Subscription: 
      - Endpoint: !GetAtt DynamoIndexSQS.Arn
        Protocol: "sqs"

  DynamoIndexSnsSqsPolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues:
        - !Ref DynamoIndexSQS
      PolicyDocument:
        Statement:
          - Sid: SNSMessageSQS
            Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action: 
              - "sqs:SendMessage"
              - "SQS:ReceiveMessage"
            Resource:
              - !GetAtt DynamoIndexSQS.Arn


  DynamoIndexSnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: S3Buckets
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - "sns:Publish"
              - "SNS:Subscribe"
              - "SNS:Publish"
            Resource:
              - !Ref DynamoIndexSNS

      Topics: 
        - !Ref DynamoIndexSNS

  ElasticStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ES_ENDPOINT: https://search-gumpsimagesearch-jz7atpxc4ifyh63kaahwxk4sbu.us-east-1.es.amazonaws.com
      Architectures: [arm64]
      Timeout: 8
      PackageType: Image
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageIndexDynamoTableDB
        - ElasticsearchHttpPostPolicy:
            DomainName: gumpsimagesearch
      Events:
        DDBEvent:
          Type: DynamoDB
          Properties:
            Stream: 
              !GetAtt ImageIndexDynamoTableDB.StreamArn  
            StartingPosition: TRIM_HORIZON
            Enabled: true
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./ElasticStream
      DockerTag: python3.8-v1

  DynamoIndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 5
      Architectures: [arm64]
      EventInvokeConfig:
        MaximumRetryAttempts: 1
      PackageType: Image
      Events:
        SqsJobQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt DynamoIndexSQS.Arn
            BatchSize: 1
      Policies:
        - SQSPollerPolicy:
            QueueName:
              !GetAtt DynamoIndexSQS.QueueName
        - S3CrudPolicy: 
            BucketName: 
              !Ref ResizeImageforNSS3
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageIndexDynamoTableDB
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./DynamoIndexFunction
      DockerTag: python3.8-v1
        
  ImageIndexDynamoTableDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GumpsSearchEngine
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: unique_index
          KeyType: HASH
      AttributeDefinitions:
        - 
          AttributeName: unique_index
          AttributeType: S

  ResizeImageforNSS3: 
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref DynamoIndexSNS
            Event: s3:ObjectCreated:*